[book]
authors = ["Jonas Pleyer"]
language = "en"
multilingual = false
src = "src"
title = "Scientific Computing in Rust"

[preprocessor.bib]
bibliography = "literature.bib"
hb-tpl = "render/refs_default.hbs"
